AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM execution role for GitHub Actions CI/CD deployment (cross-account compatible)'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: dev-roar-lab-hp

  BridgeRoleArn:
    Type: String
    Description: ARN of the bridge role in the shared resource account that will assume this role (e.g., arn:aws:iam::123456789012:role/bridge-role). Leave empty for same-account setup.
    Default: ''

  S3BucketName:
    Type: String
    Description: Name of the S3 bucket to deploy to (can use existing bucket or reference from another stack)

  CloudFrontDistributionId:
    Type: String
    Description: CloudFront Distribution ID for cache invalidation

Conditions:
  IsCrossAccount: !Not [!Equals [!Ref BridgeRoleArn, '']]

Resources:
  # IAM Role for GitHub Actions
  GitHubActionsRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RoleName: !Sub '${ProjectName}-GitHubActionsDeployRole'
      Description: IAM execution role for GitHub Actions to deploy to S3 and invalidate CloudFront
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: !If
              - IsCrossAccount
              - AWS: !Ref BridgeRoleArn
              - AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeployToS3AndCloudFront
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3BucketAccess
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
              - Sid: CloudFrontInvalidation
                Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: GitHub Actions CI/CD

Outputs:
  GitHubActionsRoleArn:
    Description: ARN of the IAM execution role for GitHub Actions (use this value in GitHub Secrets as AWS_EXECUTION_ROLE_ARN)
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'

  GitHubActionsRoleName:
    Description: Name of the IAM execution role for GitHub Actions
    Value: !Ref GitHubActionsRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
