name: Deploy

# Trigger only after CI workflow completes successfully on main branch
# This ensures deployment only happens when all tests pass
on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [main]
  workflow_dispatch: # Allow manual trigger for emergency deployments

permissions:
  id-token: write
  contents: read
  actions: read # Required to download artifacts from CI workflow
  pages: write # Required for GitHub Pages deployment

jobs:
  # Detect which files changed to optimize deployment execution
  changes:
    name: Detect Changes
    # Only run if CI workflow succeeded (skip for manual dispatch as it doesn't have workflow_run context)
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # For workflow_dispatch, checkout the current branch
          # For workflow_run, checkout the triggering commit
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || github.event.workflow_run.head_sha }}

      - name: Check for deployment-related changes
        id: filter
        run: |
          # For workflow_dispatch, detect changes using git diff
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Compare with the previous commit
            CHANGED_FILES=$(git diff --name-only HEAD~1)
          else
            # For workflow_run, use GitHub API to get changed files from the commit
            CHANGED_FILES=$(gh api \
              repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_sha }} \
              --jq '.files[].filename')
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo ""

          # Check if app-related files changed
          if echo "$CHANGED_FILES" | grep -qE '^(src/|public/|package\.json|package-lock\.json|next\.config\.ts|tailwind\.config\.ts|tsconfig\.json|postcss\.config\.mjs)'; then
            echo "app=true" >> $GITHUB_OUTPUT
            echo "App files changed: true"
          else
            echo "app=false" >> $GITHUB_OUTPUT
            echo "App files changed: false"
          fi

          # Check if docs-related files changed
          if echo "$CHANGED_FILES" | grep -qE '^(src/.*\.stories\.tsx|\.storybook/|typedoc\.json)'; then
            echo "docs=true" >> $GITHUB_OUTPUT
            echo "Docs files changed: true"
          else
            echo "docs=false" >> $GITHUB_OUTPUT
            echo "Docs files changed: false"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

  # Single approval gate for both deployments
  # This job requires manual approval and creates a checkpoint
  approval:
    name: Await Deployment Approval
    needs: changes
    # Only run if there are app or docs changes (or manual dispatch)
    if: |
      github.event_name == 'workflow_dispatch' ||
      (needs.changes.outputs.app == 'true' || needs.changes.outputs.docs == 'true')
    runs-on: ubuntu-latest
    # Require manual approval via GitHub Environment
    # Configure in: Settings → Environments → production
    environment: production

    steps:
      - name: Approval checkpoint
        run: |
          echo "## Deployment Approved :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Approved by: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "Triggered by: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The following deployments will proceed:" >> $GITHUB_STEP_SUMMARY
          echo "- AWS S3 + CloudFront" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub Pages (Documentation)" >> $GITHUB_STEP_SUMMARY

  # Deploy to AWS S3 + CloudFront
  deploy-aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [changes, approval]
    # Only run if app files changed (or manual dispatch)
    if: |
      github.event_name == 'workflow_dispatch' ||
      needs.changes.outputs.app == 'true'

    steps:
      # Download build artifacts from CI workflow
      # No need to rebuild - use cached artifacts for faster deployment
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # AWS authentication using OIDC and Role Chaining
      # Secrets should be configured in the 'production' Environment
      # (not Repository secrets) for additional security
      - name: Configure AWS credentials (Bridge Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BRIDGE_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Assume execution role (Role Chaining)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_EXECUTION_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-chaining: true

      - name: Deploy to S3
        run: |
          echo "Uploading to S3 bucket: ${{ secrets.S3_BUCKET_NAME }}"
          aws s3 sync out/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete

      - name: Invalidate CloudFront cache
        id: invalidation
        run: |
          echo "Creating CloudFront invalidation for distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
          INVALIDATION_ID=$(aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text)

          echo "invalidation-id=$INVALIDATION_ID" >> $GITHUB_OUTPUT

      - name: AWS deployment summary
        run: |
          echo "## AWS Deployment Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Item | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| S3 Bucket | \`${{ secrets.S3_BUCKET_NAME }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| CloudFront Distribution | \`${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Invalidation ID | \`${{ steps.invalidation.outputs.invalidation-id }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> :hourglass: CloudFront invalidation may take a few minutes to complete." >> $GITHUB_STEP_SUMMARY

  # Deploy documentation to GitHub Pages
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [changes, approval]
    # Only run if docs-related files changed (or manual dispatch)
    if: |
      github.event_name == 'workflow_dispatch' ||
      needs.changes.outputs.docs == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build documentation
        run: npm run docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Documentation deployment summary
        run: |
          echo "## Documentation Deployment Summary :book:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Item | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Deployment URL | ${{ steps.deployment.outputs.page_url }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> :sparkles: Documentation is now live!" >> $GITHUB_STEP_SUMMARY
